In [0]:
import tensorflow as tf

vector = tf.constant([[4,5,6]], dtype=tf.float32)
eucNorm = tf.norm(vector, ord="euclidean")

with tf.Session() as sess:
  print(sess.run(eucNorm))


8.774964


In [0]:
import numpy as np
import tensorflow as tf

matrix1 = [[1.0,2.0],[3.0,4.0]]
matrix2 = np.array([[1.0,2.0], [3.0,4.0]], dtype = np.float32)
matrix3 = tf.constant([[1.0,2.0], [3.0,4.0]])

print(type(matrix1))
print(type(matrix2)) 
print(type(matrix3))

tensorForM1 = tf.convert_to_tensor( matrix1,dtype =tf.float32)
tensorForM2 = tf.convert_to_tensor( matrix2,dtype =tf.float32)
tensorForM3 = tf.convert_to_tensor( matrix3,dtype =tf.float32)

print(type(tensorForM1))
print(type(tensorForM2))
print(type(tensorForM3))

<class 'list'>
<class 'numpy.ndarray'>
<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>


In [0]:

import tensorflow as tf
mat1 = tf.constant( [[4,5,6],[3,2,1]] )
mat2 = tf.constant( [[ 7,8,9],[10,11,12]] )
mult = tf.multiply( mat1, mat2)
dotproduct = tf.matmul( mat1, tf.transpose(mat2))
with tf.Session() as sess:
  print(sess.run(mult))
  print(sess.run(dotproduct))


[[28 40 54]
 [30 22 12]]
[[122 167]
 [ 46  64]]


In [0]:
import tensorflow as tf
x=[[1,2,3],[4,5,6]]
x=tf.convert_to_tensor(x)
xtrans = tf.transpose(x)

y = ( [ [[1,2,3],[6,5,4]], [[4,5,6],[3,6,3]] ])
y =tf.convert_to_tensor(y)
ytrans = tf.transpose(y,perm=[0,2,1])

with tf.Session() as sess:
  print("--X--")
  print(sess.run(xtrans))
  print("--Y with perm--")
  print(sess.run(ytrans))


--X--
[[1 4]
 [2 5]
 [3 6]]
--Y with perm--
[[[1 6]
  [2 5]
  [3 4]]

 [[4 3]
  [5 6]
  [6 3]]]


In [0]:
# Code for linear equation 
import tensorflow as tf
#vars for equation 1
x1 = tf.constant(3, dtype=tf.float32)
y1 = tf.constant(2, dtype=tf.float32)
point1=tf.stack([x1,y1])
#vars for equation 2
x2 = tf.constant(4, dtype=tf.float32)
y2 = tf.constant(-1, dtype=tf.float32)
point2=tf.stack([x2,y2])
#solve for AX=C
X=tf.transpose(tf.stack ([point1,point2]))
C=tf.ones((1,2), dtype=tf.float32) # ones returns a matrix of all 1, with 1 row and 2 cols
A = tf.matmul(C, tf.matrix_inverse(X))
with tf.Session() as sess:
	X= sess.run(X)
	print(X)
	A = sess.run(A)
	print(A)
b= 1/A[0][1]
a= -b*A[0][0]
print( "Linear equation is: y={a}x+{b}".format(a=a,b=b)) 


[[ 3.  4.]
 [ 2. -1.]]
[[0.27272728 0.09090909]]
Linear equation is: y=-2.9999999999999996x+10.999999672174463
